#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

EXTRA_COMPONENT_DIRS := ../sdk

PROJECT_NAME := hello-world

include $(IDF_PATH)/make/project.mk

